### ISSUE TITLE
レビューサンプル

### ISSUE THREAD

**Issue by YutaUra** [YutaUra/YCU-Programing#3]
三輪さんの[ここ](https://github.com/YutaUra/YCU-Programing/blob/master/Python_understanding/%241_str/test.md)のところいい感じだね！
これこれをあれあれにするともっとわかりやすいかも
@ShiroooMARISON

**Comment by yoshiyukids** [comment]
@YutaUra @ShiroooMARISON 
たしかに！！

**Comment by yoshiyukids** [comment]
[koko](https://docs.python.org/ja/3/library/stdtypes.html)

**Comment by yoshiyukids** [comment]
[なるほど](https://biz.trans-suite.jp/4418)
